create table S6_LRS
 (Geom SDO_GEOMETRY);
 
 select SR.ID,
 SDO_GEOM.SDO_LENGTH(SR.GEOM, 1, 'unit=km') DISTANCE,
 ST_LINESTRING(SR.GEOM) .ST_NUMPOINTS() ST_NUMPOINTS
from STREETS_AND_RAILROADS SR, MAJOR_CITIES C
where SDO_RELATE(SR.GEOM,
 SDO_GEOM.SDO_BUFFER(C.GEOM, 10, 1, 'unit=km'),
'MASK=ANYINTERACT') = 'TRUE'
and C.CITY_NAME = 'Koszalin';

insert into S6_LRS
 select SR.geom
 from STREETS_AND_RAILROADS SR
 where SR.ID = 56;
 
 
 
select
 SDO_GEOM.SDO_LENGTH(S6.GEOM, 1, 'unit=km') DISTANCE,
 ST_LINESTRING(S6.GEOM) .ST_NUMPOINTS() ST_NUMPOINTS
from S6_LRS S6;

update S6_LRS S6
set geom = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, 276.681);

INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('S6_LRS','GEOM',
MDSYS.SDO_DIM_ARRAY(
 MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
 MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
 MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1) ),
 8307);
 
 CREATE INDEX lrs_routes_idx ON S6_LRS(geom) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
 
 select SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500 from s6_lrs;

 select SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT from s6_lrs;
 
 select SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 from S6_LRS;
 
select SDO_LRS.get_next_shape_pt(S6.GEOM, sdo_lrs.find_measure(s6.geom,c.geom)) WJAZD_NA_S6
from S6_LRS S6, MAJOR_CITIES C where C.CITY_NAME = 'Slupsk';

select SDO_GEOM.SDO_LENGTH(SDO_LRS.OFFSET_GEOM_SEGMENT(S6.GEOM, M.DIMINFO, 50, 200, 50,
 'unit=m arc_tolerance=1'),1,'unit=km') KOSZT
from S6_LRS S6, USER_SDO_GEOM_METADATA M
where M.TABLE_NAME = 'S6_LRS' and M.COLUMN_NAME = 'GEOM';
